default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: training_demo_development

test:
  <<: *default
  database: training_demo_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

  cable:
    url: <%= ENV["DATABASE_URL"] %>
